version: '3.7'

services:
  panel:
    build:
      context: ./services/panel
      dockerfile: Dockerfile.dev
    command: >
      sh -c "
      panel serve index ${ARGS_1} & 
      panel serve lidar-nn ${ARGS_2} &
      panel serve ufunc-correct ${ARGS_3} &
      panel serve when-rad ${ARGS_4} &
      panep serve get-dem ${ARGS_5}"
    volumes:
      - /usr/src/app/
    expose:
      - 5006
      - 5007
      - 5008
      - 5009
    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./services/webserver/nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - panel
    networks:
      - app-network
   
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email charlesisaacstern@gmail.com --agree-tos --no-eff-email --force-renewal -d apps.cstern.io

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/apps.cstern.io/volumes/web-root/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/apps.cstern.io/services/webserver/dhparam/
      o: bind

networks:
  app-network:
    driver: bridge
